# Generated by Django 4.2.20 on 2025-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('full_name', 'Full Name'), ('job', 'Job'), ('email', 'Email'), ('domain', 'Domain'), ('phone', 'Phone Number'), ('company', 'Company'), ('text', 'Text'), ('integer', 'Integer'), ('address', 'Address')], default='ful_name', max_length=50),
            preserve_default=False,
        ),
    ]
